# Generated by Django 3.2.6 on 2023-03-17 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='paciente',
            fields=[
                ('id', models.SmallIntegerField(blank=True, default=None, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=30)),
                ('edad', models.SmallIntegerField(blank=True, default=None, null=True)),
                ('sexo', models.CharField(max_length=10)),
                ('fechaNacimiento', models.DateTimeField()),
                ('prioridad', models.CharField(max_length=30)),
                ('paisRecidencia', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=60)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
    ]
